trigger:
  branches:
    include:
      - main

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
- checkout: self
  fetchDepth: 0
  persistCredentials: true
  clean: true

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '20.x'

- task: CmdLine@2
  displayName: "⏳ Running git pull"
  inputs:
    script: |
      git fetch          
      git switch main

- task: CmdLine@2
  displayName: "🦋 Checking status"
  continueOnError: false
  inputs:
    script: |
      FILES=$(find ./.changeset -name "*.md")
      if [ -z "$FILES" ]; then
        echo "No changesets found"
        exit 1
      else
        echo "There are changesets!"
      fi

- task: Cache@2
  inputs:
    key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
    path: $(pnpm_config_cache)
  displayName: Cache pnpm

- script: |
    corepack enable
    corepack prepare pnpm@latest-8 --activate
  displayName: "📦 Setting up PNPM"

- script: pnpm config set store-dir $(pnpm_config_cache)
  displayName: "💾 Create cache"

- task: CmdLine@2
  displayName: "⏳ Installing dependencies"
  inputs:
    script: |
      pnpm install

- task: NpmAuthenticate@0
  inputs:
    workingFile: .npmrc

- task: CmdLine@2
  displayName: "🚀 Versioning & publishing Changesets"
  condition: succeeded()
  env: 
    GIT_CREDENTIALS: $(System.AccessToken)
  inputs:
    script: |
      git config --global user.email "diageotech.support@comprend.com"
      git config --global user.name "Diageo release pirate"
      pnpm changesets:version
      git add .
      pnpm changesets:publish
      git commit -m "chore: version changesets [skip ci]"
      git push --follow-tags
      git tag

- task: CmdLine@2
  displayName: "📜 Creating monorepo changelog"
  env: 
    GIT_CREDENTIALS: $(System.AccessToken)
  inputs:
    script: |
      pnpm run ci:changelog

